<%@ Page Language="C#" AutoEventWireup="true" CodeFile="webcast.aspx.cs" Inherits="webcast" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>News worthy Webcast : Powered by 24Framesdigital</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Roboto:100,300,400,500,700,900" rel="stylesheet" />
    <script src="//cdn.24fd.com/resources/js/jquery11m.js"></script>
    <script type="text/javascript" src="//cdn.24fd.com/resources/js/json2.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js"></script>
    <script type="text/javascript" src="//cdn.24fd.com/e20/resources/jw8.5.6/jwplayer.js"></script>
    <script type="text/javascript">jwplayer.key = "0cAn/sx6+MBeHm6dn1im6+iV92fyl74rWkBZXLLbjCg=";</script>
    <link href="//cdn.24fd.com/resources/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/webcastpage1.css" rel="stylesheet" />
    <link href="css/chat.css" rel="stylesheet" />
    <link href="css/poll.css" rel="stylesheet" />
    <script type="text/javascript" src="//cdn.24fd.com/resources/js/jquery.downCount.js"></script>
    <link rel="icon" href="//cdn.24fd.com/resources/24fd.gif" type="image/gif" sizes="16x16" />
    <!--<script type="text/javascript" src="js/fetchdata_nano_ppt.js?vgfxhhxxh"></script>-->
    <script src="//cdn.24fd.com/resources/js/bootstrap.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.24fd.com/resources/js/html5shiv-printshiv.js"></script>
      <script src="//cdn.24fd.com/resources/js/respond.js"></script>

    <![endif]-->
    <script src="../Scripts/jquery.signalR-2.4.2.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../signalr/hubs"></script>

    <script src="//cdn.24fd.com/resources/js/jquery.charactercounter.js"></script>


</head>
    <body>
        <form runat="server">
                        <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
            <asp:Label ID="Label1" runat="server" Text=""></asp:Label>

            <br />

            <button class="btn ask-btn" id='next'>Submit AJAX</button>

        </form>
<script>
    $(document).ready(function () {

        //alert('hello');
    });

    // Click handler for the 'next' button
    $('#next').off().on('click', function (e) {
        //alert('hii');

        e.preventDefault();
        savepoll();
       
    });

    function savepoll() {
        //alert('savepoll');
       
        var abc = {
            "name": "hello hello",
            "email": "hello@hello.com",
            "eventid": "24FDEvent_1013",
            "Replaceurl": "/events/21186/",
            "Question": "test123",
            "Answer": "a"
        }
        // alert(JSON.stringify(abc));
        $.ajax({
            type: "POST",
            url: "../home/AddPollAnsData",
            data: JSON.stringify(abc),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (r) {
                //alert(result.d);
            }
        });
    }
</script>
   
</body>



</html>

